# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/dji_thermal_sdk',
                'doc_host': 'https://lyuhaitao.github.io',
                'git_url': 'https://github.com/lyuhaitao/dji_thermal_sdk',
                'lib_path': 'dji_thermal_sdk'},
  'syms': {'dji_thermal_sdk.core': {'dji_thermal_sdk.core.foo': ('core.html#foo', 'dji_thermal_sdk/core.py')}}}
